spring:
  # 配置数据源信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource    # SpringBoot默认使用的数据源类型
    driver-class-name: com.mysql.cj.jdbc.Driver   # 驱动类 （8版本的）
    url: jdbc:mysql://localhost:3306/testsql?characterEncoding=utf-8&useSSL=false
    username: root
    password: Hulailai28951378
  profiles:
    active: dev # 表示开发环境

token:
  key: user